### ISSUE TITLE
Multiple concurrent processes

### ISSUE THREAD

**Issue by zoink** [jungerm2/Twper#2]
Have you tried running multiple processes/jobs with Twper? 

I am running into rate limit issues with other scrapers (Twint, twitterscraper), I'm not sure if I will have the same problems with Twper. Thanks.

**Comment by jungerm2** [comment]
I haven't tried it as the rate was sufficient for my application. However since it's using asynchronous io it should be thread safe. 

Please let me know if you've tried it, any feedback is appreciated!
